### ISSUE TITLE
Make product-config a custom resource [Was: Switch from JSON to YAML for the product configuration]

### ISSUE THREAD

**Issue by maltesander** [stackabletech/product-config#22]
## The problem

Currently, the product configuration is an ad-hoc (home-grown) JSON file with a long list of property specifications. There are multiple problems with this approach:

- The file needs to distributed across all operators which is error prone and probably will require a restart.
- Field validation rules are implemented here. There is hardly any code reuse, which requires a lot of testing.
- The command line of the entry point to a role is incomplete. It only specifies arguments but not the actual program to run, which is hard coded in each operator.

## Proposed solution

Switch from the home-grown JSON to a YAML format that can be configured and validated as a custom resource in K8S.

Advantages:

- Operators are notified about changes.
- Field validation can be done the K8S CRD using the `openapi` format and rules. Less code.
- The complete command line entry point of a role can be configured here and is transparent to users.

Disadvantages:

- It's not clear to what extent the `kube-rs` supports openapi validation rules. Some work and discussion have been taking place here: https://github.com/clux/kube-rs/issues/129

**Comment by razvan** [comment]
IMO, cli configuration in `product-config` should be defined such that ordering is natural (no `Cli(usize)` in form of `"order": 42` or such).

I see two options:

* use an array to define the entire command line. This would be similar to what Docker does with `CMD` and `ENTRYPOINT`. Customers would change arguments using role group overrides.
* use a string and template variables (which product-config doesn't support at the moment). Customers would change arguments using variable overrides.

**Comment by soenkeliebau** [comment]
Closing this for now, we will address this at some point, when we create a roadmap for the product config framework.
